[tool.poetry]
name = "have-a-good-sleep"
version = "1.0.0"
description = "ğŸ•´ğŸ•´ğŸ•´ SwitchBotã®APIã‚’åˆ©ç”¨ã—ã¦ã€22æ™‚ã«ãªã£ãŸã‚‰å¾ã€…ã«ãƒ©ã‚¤ãƒˆã‚’æš—ãã™ã‚‹ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
requests = "^2.32.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
black = "^24.4.2"
isort = "^5.12.0"
mypy = "^1.7.0"
pytest = "^8.2.1"
types-requests = "^2.31.0.20240406"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
